# Generated by Django 4.1.5 on 2023-07-06 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(default=0, max_length=13, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,10}$')]),
        ),
    ]
